Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: io.nellis.MainFunction
      CodeUri: /Users/chris/IdeaProjects/basicJoker
      Runtime: java11